# Generated by Django 3.2.3 on 2021-06-02 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoUniApp', '0002_auto_20210601_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordatorios',
            name='fechafinal',
            field=models.DateField(verbose_name='Fecha Hasta'),
        ),
        migrations.AlterField(
            model_name='recordatorios',
            name='texto',
            field=models.TextField(max_length=200),
        ),
    ]
